apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  namespace: itu-minitwit-monitoring-ns
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'prometheus'

        scrape_interval: 15s

        scheme: http

        static_configs:
          - targets: ["itu-minitwit-backend.itu-minitwit-backend-ns.svc:80"]

