apiVersion: apps/v1
kind: Deployment
metadata:
  name: itu-minitwit-monitoring-prometheus
  namespace: itu-minitwit-monitoring-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itu-minitwit-monitoring-prometheus
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: itu-minitwit-monitoring-prometheus
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: itu-minitwit-monitoring-prometheus
        image: kongborup/itu-minitwit-monitoring-prometheus
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 2
          successThreshold: 1
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-conf
---
apiVersion: v1
kind: Service
metadata:
  name: itu-minitwit-monitoring-prometheus
  namespace: itu-minitwit-monitoring-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: itu-minitwit-monitoring-prometheus
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itu-minitwit-monitoring-prometheus
  namespace: itu-minitwit-monitoring-ns
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - prometheus.rhododevdron.dk
    secretName: tls-secret-prometheus
  - hosts:
    - prometheus.rhododevdron.swuwu.dk
    secretName: tls-secret-prometheus-swuwu
  rules:
  - host: prometheus.rhododevdron.dk 
    http: &http_rules
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: itu-minitwit-monitoring-prometheus
            port:
              number: 80
  - host: prometheus.rhododevdron.swuwu.dk
    http: *http_rules