apiVersion: apps/v1
kind: Deployment
metadata:
  name: itu-minitwit-monitoring-prometheus
  namespace: itu-minitwit-monitoring-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itu-minitwit-monitoring-prometheus
  template:
    metadata:
      labels:
        app: itu-minitwit-monitoring-prometheus
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: itu-minitwit-monitoring-prometheus
        image: kongborup/itu-minitwit-monitoring-prometheus
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: itu-minitwit-monitoring-prometheus
  namespace: itu-minitwit-monitoring-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: itu-minitwit-monitoring-prometheus
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itu-minitwit-monitoring-prometheus
  namespace: itu-minitwit-monitoring-ns
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: prometheus.rhododevdron.dk 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: itu-minitwit-monitoring-prometheus
            port:
              number: 80