apiVersion: apps/v1
kind: Deployment
metadata:
  name: itu-minitwit-monitoring-grafana
  namespace: itu-minitwit-monitoring-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itu-minitwit-monitoring-grafana
  template:
    metadata:
      labels:
        app: itu-minitwit-monitoring-grafana
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: itu-minitwit-monitoring-grafana
        image: kongborup/itu-minitwit-monitoring-grafana
        env:
        - name: PROMETHEUS_HOST
          value: "itu-minitwit-monitoring-prometheus"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: itu-minitwit-monitoring-grafana
  namespace: itu-minitwit-monitoring-ns
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: itu-minitwit-monitoring-grafana

