apiVersion: v1
kind: Secret
metadata:
  name: itu-minitwit-backend-secrets
  namespace: itu-minitwit-backend-ns
type: Opaque
data:
  CONNECTION_STRING: c2VydmVyPWl0dS1taW5pdHdpdC1tc3NxbC1zZXJ2ZXIuZGF0YWJhc2Uud2luZG93cy5uZXQ7ZGF0YWJhc2U9aXR1LW1pbml0d2l0LW1zc3FsLWRhdGFiYXNlO3VzZXIgaWQ9dXd1YWRtaW47cGFzc3dvcmQ9c3d1d3VsdSF3VXdVCg==