apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: itu-minitwit-backend-secrets
  namespace: itu-minitwit-backend-ns
spec:
  encryptedData:
    CONNECTION_STRING: AgAzUc5ImeJPRljGsW9UUguqKy2+N7vtdEHGg7zGnWAMACn/UH31FyCh9zawCnz63tD2ghBROAHc9BIjLclkv4Kh6DNXhRJU5+4WTvaUAj8FM7yAg/nItfoAZ6ms8uG8dJZbZaQg3Nkvcb7OAmjPgfiKg+zoqxEruz0d2qFHMn4MHGjJ/dQFMvPZ8sH7RZCzyQWWhdp9JSvKOMt7pMFBMYTPJ8Z1xCFIp0xxIoVt/CjQCOZWcJM/hi0gPZ19sByZLrixFkk4DgP0KBTIITnu0vba+JGRj6WgkmbNP0LWqEG0eK+0toCSxC5wmdxRD+gCIbNSsCMGbJYKmVA6OndWZSao8aBoq/rmbfVTAidcJvik6mJ9ZgJuthvhHDlHsjcv6zrqquO0pqDbfxevcpBJK5hXSruwcc63RIoCOMUOLoHVt5N8SnFbD/tAC62XmjxNGL98aMh1kyvIC4KxjKKRyKY+GzXQX8PT1nFOY2hvgrGzyaLOFQciEbopMloz/NaL4QC6dt0Wc8rmZ5+bweVxK8h/F+U6AAjoJN32FajN38wwgybuCiUXMP+6KyhOuyvVc+/Hi7LSfhyMWjgIYgGpC6VXkonFKYmMwCeKdr1UUHiOXNSiUNJO+YfgZ6t4RWL5LBMQNiZmrB1MyURqoF8uShB+VzgQvjVYu9RWoAF1vnzbpF/8hbH0LIFPVBNlnIuAB0TqnbiJRPjvE+wtLHITo8ahvmTwps1vxNezNfZTmpBL8Ysz9l4eZZ2FC6YP229FlRP79iV7Qod6u1NoSs2LWAy1h4mOaS/8SCQmiwVWJJH5gDH7F3O/SvuVLGEFmQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: itu-minitwit-backend-secrets
      namespace: itu-minitwit-backend-ns

