apiVersion: v1
kind: PersistentVolume
metadata:
  name: itu-minitwit-database-pv
  namespace: itu-minitwit-backend-ns
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: database-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 127.0.0.1
    path: /mnt/md0/k8_nfs_share/database
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: itu-minitwit-database-pvc
  namespace: itu-minitwit-backend-ns
spec:
  storageClassName: database-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
