version: 2.1

# orbs:
#   azure-cli: circleci/azure-cli@1.2.0

jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.17-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  push_to_docker_hub:
    # branches:
    #   only:
    #     - master
    docker:
      - image: circleci/golang:1.17-buster
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          LABEL=$DOCKER_USERNAME/itu-minitwit-server:$TAG
          docker build -t $LABEL .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $LABEL

  # redeploy_azure:
  #   # branches:
  #   #   only:
  #   #     - master
  #   executor: azure-cli/default
  #   steps:
  #     - azure-cli/install
  #     - run:
  #         command: az -v
  #         name: Verify Azure CLI is installed

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - push_to_docker_hub:
          requires:
            - build_and_test
      # - redeploy_azure:
      #     requires:
      #       - push_to_docker_hub
