version: "3.9"

services:
  prometheus:
    build:
      context: ./prometheus
      args:
        APP_HOST: api.rhododevdron.swuwu.dk
    ports:
      - "9090:8080"

  grafana:
    build:
      context: ./grafana
    environment:
      PROMETHEUS_HOST: prometheus:8080
    ports:
      - "3000:80"
