version: "3.9"

services:
  prometheus:
    image: kongborup/itu-minitwit-monitoring-prometheus
    ports:
      - "9090:8080"

  grafana:
    image: kongborup/itu-minitwit-monitoring-grafana
    environment:
      PROMETHEUS_HOST: prometheus:8080
    ports:
      - "3000:80"
