apiVersion: apps/v1
kind: Deployment
metadata:
  name: itu-minitwit-backend
  namespace: itu-minitwit-backend-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itu-minitwit-backend
  template:
    metadata:
      labels:
        app: itu-minitwit-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: itu-minitwit-backend
        image: kongborup/itu-minitwit-server 
        env:
        - name: ENVIRONMENT
          value: "PRODUCTION"
        - name: SQLCONNSTR_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: itu-minitwit-backend-secrets
              key: CONNECTION_STRING
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: itu-minitwit-backend
  namespace: itu-minitwit-backend-ns
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: itu-minitwit-backend
