apiVersion: v1
kind: PersistentVolume
metadata:
  name: itu-minitwit-elasticsearch-pv
  namespace: itu-minitwit-logging-ns
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: logging-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 127.0.0.1
    path: /mnt/md0/k8_nfs_share/logging
    readOnly: false
