apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: itu-minitwit-elasticsearch
  namespace: itu-minitwit-logging-ns
# By default creates a 1Gi volume claim in Azure
spec:
  version: 7.1.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        securityContext: # Necessary for reasons beyond my comprehension
          fsGroup: 1000
          runAsUser: 1000
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: 0.8
              memory: 4Gi
            requests:
              cpu: 0.4
              memory: 0.5Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: itu-minitwit-sc
        resources:
          requests:
            storage: 10Gi
