apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: itu-minitwit-sc
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
  location: northeurope
allowVolumeExpansion: true
reclaimPolicy: Delete
# volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload